version: '3.4'

services:
  hias-core:
    image: hiascore:dev
    container_name: HIAS-Core
    build:
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "HIAS-Core"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - /Users/leowyizhen/DagangHalal/Code/HIAS-Core/HIAS-Core:/app
      - /Users/leowyizhen/DagangHalal/Code/HIAS-Core:/src
      - /Users/leowyizhen/vsdbg/vs2017u5:/remote_debugger:rw
      - /Users/leowyizhen/.nuget/packages/:/root/.nuget/packages:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net6.0/HIAS-Core.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true